import { writeFile } from "node:fs/promises";
import { z } from "zod";
import { apiErrorV1Schema, discoveryResponseV1Schema, galleryResponseV1Schema, machineReportV1Schema, pubkeysResponseV1Schema, receiptEnvelopeV1Schema, releaseManifestV1Schema, runStatusV1Schema, verifyReleaseRequestV1Schema, verifyReleaseResponseV1Schema } from "../src/contracts/index.js";

const document = {
  openapi: "3.1.0", info: { title: "PreFlight Release Gate API", version: "1.0.0" },
  servers: [{ url: "https://api.usepreflight.xyz" }],
  paths: {
    "/livez": { get: { responses: { "200": { description: "Process is live" } } } },
    "/readyz": { get: { responses: { "200": { description: "Dependencies are ready" }, "503": { description: "Not ready" } } } },
    "/api/v1/service": { get: { responses: { "200": { description: "Service metadata" } } } },
    "/api/v1/contracts/release-manifest/v1": { get: { responses: { "200": { description: "Frozen Release Manifest JSON Schema" } } } },
    "/api/v1/contracts/discovery/v1": { get: { responses: { "200": { description: "Frozen Discovery JSON Schema" } } } },
    "/api/v1/contracts/run-events/v1": { get: { responses: { "200": { description: "Frozen Run Events JSON Schema" } } } },
    "/api/v1/contracts/machine-report/v1": { get: { responses: { "200": { description: "Frozen Machine Report JSON Schema" } } } },
    "/api/v1/discover": { post: { requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["endpoint"], properties: { endpoint: { type: "string", format: "uri" } } } } } }, responses: { "200": { description: "Discovery-first proposed manifest", content: { "application/json": { schema: { $ref: "#/components/schemas/DiscoveryResponseV1" } } } }, "400": { $ref: "#/components/responses/Error" }, "429": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/release-manifests/draft": { post: { requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReleaseManifestV1" } } } }, responses: { "200": { description: "Validated draft; never a verdict" }, "400": { $ref: "#/components/responses/Error" }, "429": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/verify-release": { post: { parameters: [{ in: "header", name: "Idempotency-Key", required: true, schema: { type: "string", minLength: 16 } }, { in: "header", name: "PAYMENT-SIGNATURE", required: false, schema: { type: "string" } }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/VerifyReleaseRequestV1" } } } }, responses: { "200": { description: "Settlement-confirmed private report", content: { "application/json": { schema: { $ref: "#/components/schemas/VerifyReleaseResponseV1" } } } }, "402": { description: "x402 v2 challenge", headers: { "PAYMENT-REQUIRED": { schema: { type: "string" } } } }, "400": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/reports/{report_id}": { get: { security: [{ bearerCapability: [] }], parameters: [{ in: "path", name: "report_id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Private report" }, "404": { $ref: "#/components/responses/Error" }, "410": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/reports/{report_id}/receipt": { post: { security: [{ bearerCapability: [] }], parameters: [{ in: "path", name: "report_id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Idempotently minted signed receipt", content: { "application/json": { schema: { $ref: "#/components/schemas/ReceiptEnvelopeV1" } } } }, "404": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/receipts/{receipt_id}": { get: { parameters: [{ in: "path", name: "receipt_id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Public signed receipt", content: { "application/json": { schema: { $ref: "#/components/schemas/ReceiptEnvelopeV1" } } } }, "404": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/pubkeys": { get: { responses: { "200": { description: "Active and retired receipt verification public keys", content: { "application/json": { schema: { $ref: "#/components/schemas/PubkeysResponseV1" } } } } } } },
    "/api/v1/reports/{report_id}/badge": { post: { security: [{ bearerCapability: [] }], parameters: [{ in: "path", name: "report_id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Badge URL for RELEASE report" }, "409": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/badge/{report_id}.svg": { get: { parameters: [{ in: "path", name: "report_id", required: true, schema: { type: "string" } }, { in: "query", name: "token", required: true, schema: { type: "string" } }], responses: { "200": { description: "Private RELEASE badge SVG" }, "404": { description: "Unavailable" }, "409": { description: "Expired due to drift" } } } },
    "/api/v1/gallery": { get: { responses: { "200": { description: "Public redacted BLOCK/UNKNOWN gallery", content: { "application/json": { schema: { $ref: "#/components/schemas/GalleryResponseV1" } } } } } } },
    "/api/v1/runs/{run_id}/events": { get: { security: [{ bearerCapability: [] }], parameters: [{ in: "path", name: "run_id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Private ordered run-stage events", content: { "application/json": { schema: { $ref: "#/components/schemas/RunStatusV1" } } } }, "404": { $ref: "#/components/responses/Error" } } } },
    "/api/v1/reports/{report_id}/machine": { get: { security: [{ bearerCapability: [] }], parameters: [{ in: "path", name: "report_id", required: true, schema: { type: "string" } }], responses: { "200": { description: "Private machine-readable report for agents and CI", content: { "application/json": { schema: { $ref: "#/components/schemas/MachineReportV1" } } } }, "404": { $ref: "#/components/responses/Error" } } } }
  },
  components: { schemas: { ReleaseManifestV1: z.toJSONSchema(releaseManifestV1Schema), VerifyReleaseRequestV1: z.toJSONSchema(verifyReleaseRequestV1Schema), DiscoveryResponseV1: z.toJSONSchema(discoveryResponseV1Schema), RunStatusV1: z.toJSONSchema(runStatusV1Schema), MachineReportV1: z.toJSONSchema(machineReportV1Schema), VerifyReleaseResponseV1: z.toJSONSchema(verifyReleaseResponseV1Schema), ReceiptEnvelopeV1: z.toJSONSchema(receiptEnvelopeV1Schema), PubkeysResponseV1: z.toJSONSchema(pubkeysResponseV1Schema), GalleryResponseV1: z.toJSONSchema(galleryResponseV1Schema), ApiErrorV1: z.toJSONSchema(apiErrorV1Schema) }, responses: { Error: { description: "Typed API error", content: { "application/json": { schema: { $ref: "#/components/schemas/ApiErrorV1" } } } } }, securitySchemes: { bearerCapability: { type: "http", scheme: "bearer" } } }
};
await writeFile(new URL("../docs/openapi.release-gate.v1.json", import.meta.url), `${JSON.stringify(document, null, 2)}\n`);
