import { randomUUID } from "node:crypto";
import { decodePaymentResponseHeader, wrapFetchWithPaymentFromConfig } from "@okxweb3/x402-fetch";
import { ExactEvmScheme, toClientEvmSigner } from "@okxweb3/x402-evm";
import { createPublicClient, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { xLayer } from "viem/chains";

const base = process.env.RELEASE_SELFTEST_BASE_URL;
const signerValue = process.env.RELEASE_SELFTEST_SIGNER;
const manifestFile = process.env.RELEASE_SELFTEST_MANIFEST_JSON;
const probeInputFile = process.env.RELEASE_SELFTEST_PROBE_INPUT_JSON;
if (!base || !signerValue || !manifestFile) throw new Error("RELEASE_SELFTEST_BASE_URL, RELEASE_SELFTEST_SIGNER and RELEASE_SELFTEST_MANIFEST_JSON are required at runtime");
if (!/^0x[a-fA-F0-9]{64}$/.test(signerValue)) throw new Error("release selftest signer is invalid");
const manifest = JSON.parse(manifestFile) as unknown;
const nestedProbeRequest = { schema_version: "preflight.verify-release-request.v1", manifest };
const request = { schema_version: "preflight.verify-release-request.v1", manifest, probe_input: probeInputFile ? JSON.parse(probeInputFile) as unknown : nestedProbeRequest };
const endpoint = new URL("/api/v1/verify-release", base); const idempotency = randomUUID(); const gates: Array<{ gate: string; result: "PASS" | "FAIL"; detail: string }> = [];
const draft = await fetch(new URL("/api/v1/release-manifests/draft", base), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(manifest) }); gates.push({ gate: "draft", result: draft.ok ? "PASS" : "FAIL", detail: `HTTP ${draft.status}` });
const unpaid = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `${idempotency}-unpaid` }, body: JSON.stringify(request) }); gates.push({ gate: "unpaid challenge", result: unpaid.status === 402 && Boolean(unpaid.headers.get("payment-required")) ? "PASS" : "FAIL", detail: `HTTP ${unpaid.status}` });
const account = privateKeyToAccount(signerValue as `0x${string}`); const publicClient = createPublicClient({ chain: xLayer, transport: http() }); let capturedPaymentSignature: string | null = null;
const capturedFetch: typeof fetch = async (input, init) => {
  const inputHeaders = input instanceof Request ? input.headers : undefined;
  const signature = new Headers(init?.headers ?? inputHeaders).get("payment-signature");
  if (signature) capturedPaymentSignature = signature;
  return fetch(input, init);
};
const paidFetch = wrapFetchWithPaymentFromConfig(capturedFetch, { schemes: [{ network: "eip155:196", client: new ExactEvmScheme(toClientEvmSigner(account, publicClient)) }] });
let paid = await paidFetch(endpoint, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `${idempotency}-paid` }, body: JSON.stringify(request) });
for (let attempt = 0; [409, 503].includes(paid.status) && attempt < 30; attempt += 1) {
  await new Promise((resolve) => setTimeout(resolve, 2_000));
  paid = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `${idempotency}-paid` }, body: JSON.stringify(request) });
}
const paymentResponseHeader = paid.headers.get("payment-response");
const settlement = paymentResponseHeader ? decodePaymentResponseHeader(paymentResponseHeader) as { transaction?: string; status?: string } : null;
const report = await paid.json() as { report_id?: string; decision?: string; receipt?: { receipt_id?: string; signature?: string }; badge_url?: string | null; report_access?: { access_token?: string; report_url?: string } };
gates.push({ gate: "paid report", result: paid.ok && Boolean(report.report_id && report.decision) ? "PASS" : "FAIL", detail: `HTTP ${paid.status}; decision=${report.decision ?? "missing"}` }); gates.push({ gate: "settlement receipt", result: Boolean(paid.headers.get("payment-response")) || paid.ok ? "PASS" : "FAIL", detail: paid.headers.get("payment-response") ? "present" : paid.ok ? "reconciled settlement" : "missing" });
const retrieval = report.report_id && report.report_access?.access_token ? await fetch(new URL(`/api/v1/reports/${report.report_id}`, base), { headers: { authorization: `Bearer ${report.report_access.access_token}` } }) : null; gates.push({ gate: "private retrieval", result: retrieval?.ok ? "PASS" : "FAIL", detail: retrieval ? `HTTP ${retrieval.status}` : "missing capability" });
const retrievedReport = retrieval?.ok ? await retrieval.clone().json() as typeof report : report;
gates.push({ gate: "signed receipt", result: Boolean(retrievedReport.receipt?.receipt_id && retrievedReport.receipt.signature) ? "PASS" : "FAIL", detail: retrievedReport.receipt?.receipt_id ?? "missing" });
const publicReceipt = retrievedReport.receipt?.receipt_id ? await fetch(new URL(`/api/v1/receipts/${retrievedReport.receipt.receipt_id}`, base)) : null;
gates.push({ gate: "public receipt", result: publicReceipt?.ok ? "PASS" : "FAIL", detail: publicReceipt ? `HTTP ${publicReceipt.status}` : "missing receipt_id" });
const badge = retrievedReport.decision === "RELEASE" && retrievedReport.report_id && retrievedReport.report_access?.access_token ? await fetch(new URL(`/api/v1/badge/${retrievedReport.report_id}.svg?token=${encodeURIComponent(retrievedReport.report_access.access_token)}`, base)) : null;
gates.push({ gate: "release badge", result: retrievedReport.decision === "RELEASE" ? (badge?.ok && badge.headers.get("content-type")?.includes("image/svg+xml") ? "PASS" : "FAIL") : "PASS", detail: retrievedReport.decision === "RELEASE" ? (badge ? `HTTP ${badge.status}` : "missing badge") : "not RELEASE" });
const machine = report.report_id && report.report_access?.access_token ? await fetch(new URL(`/api/v1/reports/${report.report_id}/machine`, base), { headers: { authorization: `Bearer ${report.report_access.access_token}` } }) : null;
const machineJson = machine?.ok ? await machine.json() as { schema_version?: string; receipt_id?: string | null } : null;
gates.push({ gate: "machine report v1.1", result: machineJson?.schema_version === "preflight.machine-report.v1.1" && Boolean(machineJson.receipt_id) ? "PASS" : "FAIL", detail: machineJson?.schema_version ?? "missing" });
const gallery = await fetch(new URL("/api/v1/gallery", base));
gates.push({ gate: "gallery route", result: gallery.ok ? "PASS" : "FAIL", detail: `HTTP ${gallery.status}` });
const mcp = await fetch(new URL("/mcp", base), { method: "POST", headers: { "content-type": "application/json", accept: "application/json, text/event-stream", "mcp-protocol-version": "2025-03-26" }, body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/list", params: {} }) });
const mcpJson = mcp.ok ? await mcp.json() as { result?: { tools?: Array<{ name?: string }> } } : {};
gates.push({ gate: "mcp verify_release listed", result: mcpJson.result?.tools?.some((tool) => tool.name === "verify_release") ? "PASS" : "FAIL", detail: mcp.ok ? `HTTP ${mcp.status}` : `HTTP ${mcp.status}` });
const replay = capturedPaymentSignature ? await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": `${idempotency}-replay`, "payment-signature": capturedPaymentSignature }, body: JSON.stringify(request) }) : null;
gates.push({ gate: "duplicate payment replay", result: replay?.status === 409 ? "PASS" : "FAIL", detail: replay ? `HTTP ${replay.status}` : "payment signature was not captured" });
console.table(gates);
console.log(JSON.stringify({ report_id: report.report_id, decision: report.decision, settlement_tx: settlement?.transaction ?? null, receipt_id: retrievedReport.receipt?.receipt_id ?? null, badge_url: retrievedReport.badge_url ?? null }, null, 2));
if (gates.some((gate) => gate.result === "FAIL")) process.exitCode = 1;
